name: 'Update Kubernetes Deployment'
description: 'Updates a Kubernetes deployment YAML file with new image tag and digest'
inputs:
  target-repository:
    description: 'Name of the target repository'
    required: true
  image-tag:
    description: 'New image tag'
    required: true
  image-digest:
    description: 'New image digest'
    required: true
  github-token:
    description: 'GitHub token'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'upload-cloud'
  color: 'green'